### ISSUE TITLE
router.param()接受4个参数, 无法处理

### ISSUE THREAD

**Issue by Kaijun** [magicdawn/express-modern#1]

**Comment by Kaijun** [comment]
我再详细点
要是
```
modern((req, res, next) => {
  return XXXModel.findById(_id).exec()
})
```
这样是可以自动捕获error的 因为返回的是Promise, 有catch函数, 自动把next传入catch

但是实际业务, 使用aync/await的时候
```
modern( async (req, res, next) => {
  let xxx = await XXXModel.findById(_id).exec()
  res.json(xxx)
})
```
这种情况没有返回Promise, 并不能自动处理Mongoose抛出的error. 不知道怎么写才合理?

**Comment by Kaijun** [comment]
Node Version: 5.11
"mongoose": "^4.4.7",

**Comment by Kaijun** [comment]
又试了下直接throw new Error()

```
(req, res, next, id) => {
  throw new Error('error')  //可以捕获并传入next
}
```

如果是async 或者generator

```
async (req, res, next, id) => {
  throw new Error('error')  //不能被express-modern捕获
}
```

应该这就是原因把? 所以捕获不到Mongoose的Error. (~~难道是Babel转换的原因吗?~~ 换了preset 不转换generator 也是不行... )

**Comment by magicdawn** [comment]
```
async (req, res, next, id) => {
  throw new Error('error')  //不能被express-modern捕获
}
```

这个应该可以吧, 有test case的
see https://github.com/magicdawn/express-modern/blob/v0.2.0/test/async.js#L27

**Comment by Kaijun** [comment]
我忘了还有test case, 我先跑一遍测试

**Comment by magicdawn** [comment]
原因是这个

```
async (req, res, next, id) => {
  throw new Error('error')  //不能被express-modern捕获
}
```

id参数哪来的？
express 的处理函数(handler) or 中间件(middleware) 都是
- 三个参数(req, res, next)
- 或者四个参数(err, req, res, next)

把 `id` 去了, 因为会影响 `express-modern` 的判断, 取得是 `fn.length`

**Comment by magicdawn** [comment]
从其他地方去取 `id`, 不用写在形参这。

**Comment by Kaijun** [comment]
@magicdawn 哦对! 但是我用router.param('id', (req, res, next, id)=>{}) 这个传入也是4个参数的

**Comment by Kaijun** [comment]
router.param: http://expressjs.com/en/api.html#router.param

**Comment by magicdawn** [comment]
用这个 express-async-wrap, 如果你是在用 async/await 的话
这个库处理不了 `app.params` 。

**Comment by magicdawn** [comment]
express-async-wrap 也处理不了这种, 当我没说 :joy: 

https://github.com/Greenfields/express-async-wrap/blob/master/src%2Findex.js

**Comment by Kaijun** [comment]
恩 我也看了下 也没办法

**Comment by Kaijun** [comment]
但是 当 len===4时 判断arguments[2]和[3]是不是function来确定是不是next()

**Comment by Kaijun** [comment]
应该是在run里面 判断下next是arguments中的哪一个

**Comment by Kaijun** [comment]
还有个小问题是, 每个middleware function必须显性得写上所有参数, 要是不传入next, 则无法catch.

相比之下Koa在这方面做的更好, middleware只有一个next参数, 其他req, res变量都在context里.

**Comment by magicdawn** [comment]
这点我发现了~正在改

**Comment by Kaijun** [comment]
恩恩恩 我再扫一遍express文档 看看还有没有其他例外的传参.
可以filter一遍arguments, 有next就catch 没有就不catch 这样可能好一点 😄

**Comment by magicdawn** [comment]
v0.3.0 新增 router.param 支持.

BTW 加了这一行, coverage 变成 95% 了 :joy: :joy: :joy: 
https://coveralls.io/builds/6000578/source?filename=index.js#L52

**Comment by magicdawn** [comment]
后续可能改为这种

`modern` & `modern.err`
- `modern` returns `function(req, res, next){ // blabla }`
- `modern.err` returns `function(err, res, res, next) { //blabla }`

**Comment by Kaijun** [comment]
可以可以 👍

**Comment by Kaijun** [comment]
不知道能否请教下, coveralls的coverage是怎么计算的...

**Comment by magicdawn** [comment]
> coveralls的coverage是怎么计算的

由 istanbul 得到的, 报告给 coveralls 展示的, 功能是 istanbul 实现的。具体不详。

**Comment by Kaijun** [comment]
噢 thx
